// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPIdsZuvuRZPD771QClkZD5Zt20m1H6mo',
    appId: '1:900063398806:web:4de275f6e1b6627cffebb7',
    messagingSenderId: '900063398806',
    projectId: 'quest-6b53b',
    authDomain: 'quest-6b53b.firebaseapp.com',
    storageBucket: 'quest-6b53b.appspot.com',
    measurementId: 'G-CFNBN8473J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbYO5R18B_ora1qao79L2YIzb18mIeUxk',
    appId: '1:900063398806:android:54792581913eded6ffebb7',
    messagingSenderId: '900063398806',
    projectId: 'quest-6b53b',
    storageBucket: 'quest-6b53b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP6udi0WVfykRRQq8maZLefs1tCDVkSOw',
    appId: '1:900063398806:ios:918ab2b93bec96c7ffebb7',
    messagingSenderId: '900063398806',
    projectId: 'quest-6b53b',
    storageBucket: 'quest-6b53b.appspot.com',
    iosBundleId: 'com.example.quest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP6udi0WVfykRRQq8maZLefs1tCDVkSOw',
    appId: '1:900063398806:ios:918ab2b93bec96c7ffebb7',
    messagingSenderId: '900063398806',
    projectId: 'quest-6b53b',
    storageBucket: 'quest-6b53b.appspot.com',
    iosBundleId: 'com.example.quest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPIdsZuvuRZPD771QClkZD5Zt20m1H6mo',
    appId: '1:900063398806:web:cb6b07243f13d1e5ffebb7',
    messagingSenderId: '900063398806',
    projectId: 'quest-6b53b',
    authDomain: 'quest-6b53b.firebaseapp.com',
    storageBucket: 'quest-6b53b.appspot.com',
    measurementId: 'G-NPSC2Z07QT',
  );

}